### ISSUE TITLE
janus_template_role question

### ISSUE THREAD

**Issue by stephenrawls** [Noblis/INVSC-janus#28]
Hi,

I have a question about the intended use of `janus_template_role`.

First, I am repeating all the possible values of this enumeration:
`ENROLLMENT_11, VERIFICATION_11, ENROLLMENT_1N, IDENTIFICATION, CLUSTERING`

1) I assume I know what VERIFICATION_11 and ENROLLMENT_1N mean (in the first case, the template will be used for the one-to-one verification protocol; in the second case, the template will be used for the one-to-n search protocol, and it is being enrolled to the gallery).  I am guessing that IDENTIFICATION means that the template will be used in the one-to-n search protocol and will be used as a probe? I am unsure what ENROLLMENT_11 would mean. Can you confirm my previous descriptions, and also explain ENROLLMENT_11?

2) Does the presence of these enrollment types mean that we can assume the test harness will call `create_template()` separately for the identification protocol and the verification protocol for templates that happen to be included in both protocols? If not, it is unclear what these `template_role` hints can be used for, if there is no guarantee that the test harness will pass them to us. If so, it seems that the test harness would be repeating work unnecessarily unless an implementation actually made use of these hints.

3) The presence of this comment in the `janus_create_template()` function seems to indicate that we are prohibited from actually making use of these hints.  (I'm unsure what use we would make out of them, I'm just trying to understand their purpose in the API)

> All media necessary to build a complete template will be passed in at
>  one time and the constructed template is expected to be suitable for
>  verification and search.

If all templates we create are supposed to be suitable for both verification and search (which seems reasonable to me, by the way), that seems to imply that we aren't allowed to create different templates depending on the value of `janus_template_role`.

Can you explain the intended use of `janus_template_role`?

Thanks,
Stephen Rawls (ISI)

**Comment by JordanCheney** [comment]
Hi Stephen,

This was created based on what NIST had seen in it's commercial FR evaluations, where vendors liked to create different templates for different use cases.

1) I am going to let NIST speak to the roles they see for each of these values.

2) You can assume that the test harness will call `create_templates()` with the proper value so templates that occur multiple times will be created multiple times, each with the correct role. 

3) This was poorly worded by me. I was trying to convey that there is no more `janus_flatten_template` and that the output of `janus_create_template()` should be ready for whatever role is intended for it, verification, search etc. not that the template has to be ready for both roles simultaneously.

**Comment by paddygr** [comment]
Hi Stephen,

The intent is to support an end-state in which a developer is free to use different representations for 1:1 and 1:N.  This is quite common in commercial face, finger, and iris implementations, often with larger templates being used in 1:N.   The role additionally gives you freedom to develop asymmetric templates so the 1:N search template could have different length and content than a 1:N enrollment (gallery) template.  For example, suppose a fast 1:N gallery is implemented using a tree or hash.  This may necessitate computation of data that does not need to be present in the 1:N search template.  A similar situation can occur for multi-stage search templates.  Also, asymmetric templates can support gallery training.

So to answer your questions
1.  Enrollment_11 indicates the template is the reference template. Verification_11 is compared with it, later. Just because many implementations have identical representations for these, doesn’t mean all do.  I have a smart card that has asymmetric fingerprint templates for example.
2.  The test harnesses will assign the correct role.  If the same input imagery is used in multiple Janus evaluations, then this will duplicate effort IF the particular algorithm behaves that way.  

Best,
Patrick Grother

**Comment by stephenrawls** [comment]
Hi Patrick,

Thanks for the explanation, I understand now.

I'm still unsure how we'd make use of Enrollment_11 and Verification_11 differently, given that the verification function has to be symetric (see comment below from API), but I suppose we can always just treat them the same if we want to.

```
* The returned \p similarity score is \em symmetric. In other words, swapping
* the order of \p a and \p b will not change \p similarity.
```

That brings up another question, though. Is it guaranteed that we will always have one Enrollment_11 template and one Verification_11 template passed to the `janus_verify()` function (which could appear in any order in the arguments)? Or is it possible that we would be comparing an Enrollment_11 template with another Enrollment_11 template, for example?

Thanks,
Stephen Rawls (ISI)

**Comment by paddygr** [comment]
Stephen,

I'd advocate to: a) drop the requirement that the similarity score be symmetric (they're sometimes not); and b) allow the algorithm to throw an error if anything other than (enrol_template, verif_template) is passed to janus_verify i.e. order and semantics are fixed.  

Best,
Patrick

**Comment by JordanCheney** [comment]
I agree that the requirement for symmetry should be removed. I can update the parameter names of the `janus_verify` function to reflect the fixed ordering

**Comment by stephenrawls** [comment]
Okay, sounds good to me. Thanks for clearing that up!

**Comment by JordanCheney** [comment]
The documentation and signature of `janus_verify` have been updated in 8945de357e0ecd6a8a2c8557a3dc1d1c7376674a
