### ISSUE TITLE
Gallery insert and remove

### ISSUE THREAD

**Issue by nxwhite-str** [Noblis/INVSC-janus#33]
We're concerned about the runtime performance and gallery size impact of janus_gallery_insert and janus_gallery_remove.  This form of incremental gallery construction may require that a gallery is recreated from scratch every time insert or remove is called.  Furthermore, even if there is a call such as "janus_prepare_gallery" as in issue #31, performers may pay one of the following penalties.  1) significantly increased gallery size due to keeping additional media or encodings for each enrolled template necessary to re-optimize the gallery for search, or 2) reduced search performance from not having the data necessary for the best gallery representation.  

We understand from discussions with IARPA that the API will be used for research purposes only, and will not be targeted for operational use.  Batch gallery construction will always be better than (or equal to) incremental construction, although incremental construction would certainly be useful for operational deployments.  

So, our question is will this incremental vs. batch gallery construction performance be studied by NIST, and is this a research question that the API should be designed to answer?  

If not, we recommend removing these API calls, and having a gallery construction be a batch operation that constructs an immutable gallery.  For our team, this will result in greatly reduced gallery sizes and much more straightforward book-keeping for gallery construction.

**Comment by JordanCheney** [comment]
Hi sorry for the slow response. I am tagging NIST (@paddygr) so that they can add their thoughts if they have any (they were interested in these tests). I have also asked IARPA to comment as this discussion is a more philosophical one of how closely should the Janus API mirror possible future operational use cases.

From Noblis' perspective, even though this is a research-only API, we would like to test things that are operationally relevant. These functions are examples of questions we get from transition partners who do care about this kind of thing. If all of the performers have O(N) performance for incremental construction and removal because that greatly boosts your 1-N accuracy or search speed that is feedback we can give to the agencies that eventually would like to adopt this technology. This helps them prepare for some of the differences between the Janus program and the awesome work you guys are doing and more traditional FR, which has a different set of limitations.

**Comment by JordanCheney** [comment]
@ericsonl @tma4321 any input you have here would very helpful

**Comment by tma4321** [comment]
Keep both incremental and batch gallery construction in the API.  It sounds like galleries should not be reconstructed every time an insert or remove is called unless the speed (and memory usage) is not impacted by large gallery sizes.  We can discuss the testing protocols separately.  Thank you

**Comment by paddygr** [comment]
The BAA sought sub-linear search. Known techniques for that can incur costs beyond the O(1) associated with vanilla linear galleries.  The two functions afford measurement of complexity O(log N) or whatever.

**Comment by JordanCheney** [comment]
Per NIST and IARPA these functions will remain a part of the API
